### ISSUE TITLE
Issues building the example.

### ISSUE THREAD

**Issue by tackypolishman** [Metick/DMALibrary#1]
Win11 / VS 2022

1 added leechcore.lib and vmmdll.lib to `libs` folder from https://github.com/ufrisk/MemProcFS/tree/master/includes/lib32
```build solution fails with c++ versions```

2 changed project versions to c++ 20 
```wcstombs may be unsafe issue```

3 Added `4996` to disable specific warnings
```
cannot open source file "DMALibrary/Memory/Memory.h"
Cannot open Include file "DMALibrary/Memory/Memory.h"
```

4 added `DMALibrary-Master` to `Additional Include Directories` on the `Example` project

```
unresolved external symbol ::InitKeyboard
unresolved external symbol Memory::Memory
```

5 Added `DMALibrary` to `References` under the `Example` Project 

```
Unresolved external symbol VMMDLL_MemFree
Unresolved external symbol VMMDLL_ReadEx
... etc
```

I have also tried adding the DMALibrary.lib(and the others) to a lib directory in the example project. But this is where I am currently stumped, I have remade the project several times and am unable to build the example project based on the most recent version of this repo.

**Comment by Metick** [comment]
All you have to do to getting this project to build is adding the 2 libraries in from ulfrisk, and change build mode to Release.

I assume you used Debug build hence why it couldn't find them as I haven't setup debug build of example. As for unresolved external is due to not linking the libraries. but as i said before this, it's most likely because you're building it as Debug mode.


Should you still have issues after changing to Release let me know (:

**Comment by tackypolishman** [comment]
Ah that makes sense. Thank you so much :) I really appreciate it.

Additionally, I had trouble with the 32 libs, I switched to 64 libs and used the suggestion you posted and its working fine now. 🙏 🙏 🙏

**Comment by ElopingDev** [comment]
Sorry to reopen such an old issue lol, but im having the same issue as him. I cloned the fresh repo, added vmm.lib and leechcore.lib to libs/ 
Set the build mode to release for both
Didn't work > Unresolved Externals
Added the folder containing the libs to Additional Library Directories
Added those libs to Additional Dependencies > Still not working :/ idk what im doing wrong honestly
