### ISSUE TITLE
Using pattern scanning

### ISSUE THREAD

**Issue by TheIgnorantDev** [Metick/DMALibrary#11]
I'm looking for some assistance in using the pattern scanning for this library.

When looking at the documentation for the function is seems that it requires being used like so.
`offsets::GNAMES = mem.FindSignature("48 8D 0D ?? ?? ?? ?? 8B FA 75 0F", 0x9074D30, 0xaf8c000);` 
But when scanning the pattern and knowing that the good address is `0x9274D40` the function returns NULL. I see in the comment you used single ? not ?? for your sigs but i've tried both with no success? 

Do you have any ideas of what im doing wrong. Ofc I've already init the process 

Console output
```
loading libraries...
Successfully loaded libraries!
inizializing...
dumping memory map to file...
Dumped memory map!
FPGA ID: 4
DEVICE ID: 8960
success!
[+] VMMDLL_ConfigGet ID = 4 VERSION = 0.0
CR3 fixed
[+] Found Base Address for DungeonCrawler.exe at 0x00007FF6301D0000
[+] Found Base Size for DungeonCrawler.exe at 0x000000000AF8C000
Process information of DungeonCrawler.exe
PID: 37316
Base Address: 0x7ff6301d0000
Base Size: 0xaf8c000
Unable to get the GNames
```

Code:
```
int main(std::string args[])
{
    if (!mem.Init("DungeonCrawler.exe", true, false))
    {
        std::cout << "Failed to initilize DMA" << std::endl;
        return 1;
    }
    offsets::GNAMES = mem.FindSignature("48 8D 0D ? ? ? ? 8B FA 75 0F", 0x9074D30, 0xAD692D0);
    if (offsets::GNAMES != NULL) {
        printf("We got something thats not null for GNames 0x%llx",offsets::GNAMES);
    }
    else {
        printf("Unable to get the GNames");
    }
}
```

**Comment by Metick** [comment]
Hey!

the second parameter is the start address it will look from, and the third param is till how far it will scan. usually it would be FindSignature(sig, base, base + size). 

(this is also why it's not finding it because your second param & third param are wrong, or atleast this is what i'm assuming as i highly doubt it's between the memory space of 0x9074D30 - 0xAD692D0)

**Comment by TheIgnorantDev** [comment]
Yes, It is the actual address im looking for is 0x9274D40 which does fit between my start and end addresses. So im really not sure what the issue there is.

**Comment by Metick** [comment]
> Yes, It is the actual address im looking for is 0x9274D40 which does fit between my start and end addresses. So im really not sure what the issue there is.

I don't think you understand, but 0x9274D40 does not sound like a real address to me. You're searching for GNames, which makes me assume it's UnrealEngine your sig is most likely located within the executable base address. so to search for that you wanna do

mem.FindSignature("48 8D 0D ? ? ? ? 8B FA 75 0F", base, base + size);

this way it will search over the memory from the executable to find the matching signature. 

so ex base = 0x7ff6301d0000
third param is (base + size) 0x7ff6301d0000 + 0xaf8c000 

it will now search between 0x7ff6301d0000 and 0x7FF63B15C000 to find your signature.

**Comment by TheIgnorantDev** [comment]
Ok, When trying it your way. Im still getting NULL for the address.
```
int main(std::string args[])
{
    const char* Game = "DungeonCrawler.exe";
    if (!mem.Init(Game, true, false))
    {
        std::cout << "Failed to initilize DMA" << std::endl;
        return 1;
    }
    size_t base = mem.GetBaseDaddy(Game);
    size_t baseSize = mem.GetBaseSize(Game);
    offsets::GNAMES = mem.FindSignature("48 8D 0D ? ? ? ? 8B FA 75 0F", base, base+baseSize );
    if (offsets::GNAMES != NULL) {
        printf("We got something thats not null for GNames 0x%llx",offsets::GNAMES);
    }
    else {
        printf("Unable to get the GNames");
    }
}
```

**Comment by Metick** [comment]
Are you sure the signature is correct? cuz that should work if it's correct.

**Comment by TheIgnorantDev** [comment]
The signature is correct as it works in IDA to retrieve the GNames, I also tried the one I have for GWorld. This evening I will try another game such as CS2 and see if I can get it working there. If so I will just close the ticket. If not I have need some help investigating the issue.

**Comment by Metick** [comment]
All I can say is, it's not a library issue. It's something wrong on your end.

**Comment by TheIgnorantDev** [comment]
Some feedback on this issue. There was something wrong with the project entirely. I was trying to add imgui as well and was getting all kinds of linker errors. So for anyone else with this issue. Try making a test project first and trying it there. As soon as I created a different project everything started working again.
