### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by VMWRITE** [Metick/DMALibrary#12]
I got BSOD everytime when tried to use call_function or just rewrite IAT/EAT function for further hooking

**Comment by Metick** [comment]
Make sure you're doing it correctly. especially when hooking a function from system space with DMA.

**Comment by VMWRITE** [comment]
Well. I tried to hook a PeekMessageW for tests. After a WPM my system is crashing because it starting killing all process (ntoskrnl.exe, svchosts.exe and etc. system apps)

**Comment by Metick** [comment]
Because when you use DMA to hook something you create a system-wide hook, so every single process will go through your hook. that calls PeekMessageW

**Comment by VMWRITE** [comment]
Well. It's a possible to hook/patch it for a single process ?

**Comment by Metick** [comment]
You could attempt to hook a function within the process, rather than hook the system dlls that are shared across all processes.

**Comment by VMWRITE** [comment]
I'll test it. Thx
