### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by hypr1x** [Metick/DMALibrary#13]
Getting error: Failed to initialize keyboard hotkeys through kernel
idk why

**Comment by Metick** [comment]
Try restarting winlogon.exe or restart your target computer.

**Comment by lishaoju** [comment]
> 尝试重新启动winlogon.exe或重新启动目标计算机。
I have restarted many times, but still cannot initialize. I am still unable to obtain QueryValue

**Comment by lishaoju** [comment]
> 尝试重新启动winlogon.exe或重新启动目标计算机。

I have restarted many times, but still cannot initialize. I am still unable to obtain QueryValue

**Comment by Metick** [comment]
> > 尝试重新启动winlogon.exe或重新启动目标计算机。
> 
> I have restarted many times, but still cannot initialize. I am still unable to obtain QueryValue

Could you provide more information about the issue so I actually know what's happening?

**Comment by lishaoju** [comment]
> > > 尝试重新启动winlogon.exe或重新启动目标计算机。
> > 
> > 
> > 我已经重新启动了很多次，但仍然无法初始化。我仍然无法获取 QueryValue
> 
> 您能否提供有关该问题的更多信息，以便我真正了解发生了什么？

eat_map->cMap == NULL

**Comment by Zhanytrix** [comment]
Having the same issue

**Comment by Zhanytrix** [comment]
To be precise, inside of `InputManager.cpp` it fails to get winversion because inside of `Registry.QueryValue()` it fails the:

```
if (!mem.vHandle)
	return "";
```
and returns nothing

**Comment by Metick** [comment]
Make sure you initialize the mem first using mem.init("executable");

**Comment by Zhanytrix** [comment]
Yes thank you for your time, problem solved.
For anyone with that problem ->

I was creating an object ```Memory mem``` but it was already in the library, I just used that one and it worked.
