### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by AtomicBool** [Metick/DMALibrary#19]
23H2 22631.3810
offset 0x3690 changed to 0x36a8
Tested 0x36a8 works

**Comment by htrshtsr** [comment]
ur a god

**Comment by htrshtsr** [comment]
> 23H2 22631.3810 offset 0x3690 changed to 0x36a8 Tested 0x36a8 works

how did you find that tho

**Comment by Metick** [comment]
> 23H2 22631.3810 offset 0x3690 changed to 0x36a8 Tested 0x36a8 works

Thanks, I'll take a look at it when i have time and then update the library if anything did change.

**Comment by Metick** [comment]
![image](https://github.com/user-attachments/assets/f970dc20-b495-4583-8153-57bb58a28792)

Looks like you're right, is 23H2 22631.3810 the start of this change?

**Comment by htrshtsr** [comment]
> ![image](https://private-user-images.githubusercontent.com/45372336/348020062-f970dc20-b495-4583-8153-57bb58a28792.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODczMzUsIm5iZiI6MTcyMDc4NzAzNSwicGF0aCI6Ii80NTM3MjMzNi8zNDgwMjAwNjItZjk3MGRjMjAtYjQ5NS00NTgzLTgxNTMtNTdiYjU4YTI4NzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEyMjM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNjIzNWI3MTRkNGU3ZGFlNDI5ZTI2OTA3NzBkNDBiNzgxZGRmZDk2NzU5ZTM2YTQyNzFjNDcwYWViZDljNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M7YcJ1b0YSAQnw39cJrCN5l9ZzqEoLUDfpY0AvcJLFM)
> 
> Looks like you're right, is 23H2 22631.3810 the start of this change?

which file is that in ida

**Comment by htrshtsr** [comment]
@Metick

**Comment by AtomicBool** [comment]
> > ![image](https://private-user-images.githubusercontent.com/45372336/348020062-f970dc20-b495-4583-8153-57bb58a28792.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODczMzUsIm5iZiI6MTcyMDc4NzAzNSwicGF0aCI6Ii80NTM3MjMzNi8zNDgwMjAwNjItZjk3MGRjMjAtYjQ5NS00NTgzLTgxNTMtNTdiYjU4YTI4NzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEyMjM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNjIzNWI3MTRkNGU3ZGFlNDI5ZTI2OTA3NzBkNDBiNzgxZGRmZDk2NzU5ZTM2YTQyNzFjNDcwYWViZDljNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M7YcJ1b0YSAQnw39cJrCN5l9ZzqEoLUDfpY0AvcJLFM)
> > Looks like you're right, is 23H2 22631.3810 the start of this change?
> 
> which file is that in ida

for the 2nd it's win32kbase.sys, 0x3110 is in win32ksgd.sys

**Comment by Metick** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/45372336/348020062-f970dc20-b495-4583-8153-57bb58a28792.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODczMzUsIm5iZiI6MTcyMDc4NzAzNSwicGF0aCI6Ii80NTM3MjMzNi8zNDgwMjAwNjItZjk3MGRjMjAtYjQ5NS00NTgzLTgxNTMtNTdiYjU4YTI4NzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEyMjM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNjIzNWI3MTRkNGU3ZGFlNDI5ZTI2OTA3NzBkNDBiNzgxZGRmZDk2NzU5ZTM2YTQyNzFjNDcwYWViZDljNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M7YcJ1b0YSAQnw39cJrCN5l9ZzqEoLUDfpY0AvcJLFM)
> > > Looks like you're right, is 23H2 22631.3810 the start of this change?
> > 
> > 
> > which file is that in ida
> 
> for the 2nd it's win32kbase.sys, 0x3110 is in win32ksgd.sys

0x3110 has never changed
