### ISSUE TITLE
its compiling as a .lib file

### ISSUE THREAD

**Issue by Broimlookingforcode** [Metick/DMALibrary#20]

**Comment by Metick** [comment]
Because it's a library

**Comment by Broimlookingforcode** [comment]
no, do u have a discord or smth so i can send u file

**Comment by Metick** [comment]
yes, and i don't want the file. It's a library that you have to link in your project if you wanna use it.

**Comment by Broimlookingforcode** [comment]
ok tks

**Comment by Broimlookingforcode** [comment]
can you please explain how to use it or smth

**Comment by Metick** [comment]
Learn how to code first

https://www.learncpp.com/
