### ISSUE TITLE
monitor

### ISSUE THREAD

**Issue by aDioS786** [Metick/DMALibrary#3]
Hi, thanks for sharing library. Is there a way to read screen size via DMA?

Thanks

**Comment by aDioS786** [comment]
Paths  under HKLM\\SYSTEM\\ doesn't seems to work tried quite a few, also under software all paths doesn't seem to work.

**Comment by Metick** [comment]
You can read it by using HIVE from VMMDll "VMMDLL_WinReg_HiveList"

example usage then: `'0x<vaCMHIVE>\ROOT\Key\SubKey'`

**Comment by aDioS786** [comment]
will try, thanks. Know a way to read monitor size?  Or if there is a way to call GetWindowRect

**Comment by Metick** [comment]
I don't know, you'll have to find something yourself
