### ISSUE TITLE
how to get gafAsyncKeyStateExport？

### ISSUE THREAD

**Issue by nethuige** [Metick/DMALibrary#31]
gafAsyncKeyStateExport = user_session_state + 0x3690;

I would like to ask how to get it using 0x3690? I used ida to open the win32ksgd.sys of the win11 22h2 version, but the offset was never found.

**Comment by Metick** [comment]
The one you're looking for is not in win32ksgd.sys. You can find the offset in win32kbase.sys, within the NtUserGetAsyncKeyState function you'll find the offset you're looking for. 
![image](https://github.com/user-attachments/assets/2450d85b-35d2-4338-930d-5f372161e4da)


as you can see on the photo attached.

**Comment by lishaoju** [comment]
> The one you're looking for is not in win32ksgd.sys. You can find the offset in win32kbase.sys, within the NtUserGetAsyncKeyState function you'll find the offset you're looking for. ![image](https://private-user-images.githubusercontent.com/45372336/363491154-2450d85b-35d2-4338-930d-5f372161e4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMTA4NzcsIm5iZiI6MTcyNTIxMDU3NywicGF0aCI6Ii80NTM3MjMzNi8zNjM0OTExNTQtMjQ1MGQ4NWItMzVkMi00MzM4LTkzMGQtNWYzNzIxNjFlNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE3MDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjY1MGZmZjg5ZWM5NWI2ZWIzZjg5MTIzYzlmYzQzMDc2MzZkOTc3M2YxYmJiYTVlNGM5YzAwN2M2MGY4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XNmkOHh7s2cW2on2PfH0YDhdhT28HtPN1G1SfGX0nxQ)
> 
> as you can see on the photo attached.

Xbox Is there any way to obtain the status

**Comment by Metick** [comment]
> > The one you're looking for is not in win32ksgd.sys. You can find the offset in win32kbase.sys, within the NtUserGetAsyncKeyState function you'll find the offset you're looking for. ![image](https://private-user-images.githubusercontent.com/45372336/363491154-2450d85b-35d2-4338-930d-5f372161e4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMTA4NzcsIm5iZiI6MTcyNTIxMDU3NywicGF0aCI6Ii80NTM3MjMzNi8zNjM0OTExNTQtMjQ1MGQ4NWItMzVkMi00MzM4LTkzMGQtNWYzNzIxNjFlNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE3MDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjY1MGZmZjg5ZWM5NWI2ZWIzZjg5MTIzYzlmYzQzMDc2MzZkOTc3M2YxYmJiYTVlNGM5YzAwN2M2MGY4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XNmkOHh7s2cW2on2PfH0YDhdhT28HtPN1G1SfGX0nxQ)
> > as you can see on the photo attached.
> 
> Xbox Is there any way to obtain the status

Do you english?

**Comment by lishaoju** [comment]
> > > 您要找的那个不在win32ksgd.sys。可以在 win32kbase.sys 中找到偏移量，在 NtUserGetAsyncKeyState 函数中，你将找到要查找的偏移量。![图像](https://private-user-images.githubusercontent.com/45372336/363491154-2450d85b-35d2-4338-930d-5f372161e4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMTA4NzcsIm5iZiI6MTcyNTIxMDU3NywicGF0aCI6Ii80NTM3MjMzNi8zNjM0OTExNTQtMjQ1MGQ4NWItMzVkMi00MzM4LTkzMGQtNWYzNzIxNjFlNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE3MDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjY1MGZmZjg5ZWM5NWI2ZWIzZjg5MTIzYzlmYzQzMDc2MzZkOTc3M2YxYmJiYTVlNGM5YzAwN2M2MGY4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XNmkOHh7s2cW2on2PfH0YDhdhT28HtPN1G1SfGX0nxQ)正如您在所附照片上看到的那样。
> > 
> > 
> > Xbox 有什么方法可以获取状态吗
> 
> 您会说英语吗？

Sorry, my English isn't very good. How do I get the button state of a game controller?

**Comment by nethuige** [comment]
thank you very much!

**Comment by nethuige** [comment]
> 您要查找的文件不在 win32ksgd.sys 中。您可以在 win32kbase.sys 中找到偏移量，在 NtUserGetAsyncKeyState 函数中您将找到您要查找的偏移量。 ![图像](https://private-user-images.githubusercontent.com/45372336/363491154-2450d85b-35d2-4338-930d-5f372161e4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTMxODUsIm5iZiI6MTcyNTI1Mjg4NSwicGF0aCI6Ii80NTM3MjMzNi8zNjM0OTExNTQtMjQ1MGQ4NWItMzVkMi00MzM4LTkzMGQtNWYzNzIxNjFlNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA0NTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxODYwN2Q1ODcxMmE0YzcyMWRiNmYzOWI5NjA1NGEyZThlODk0MzE2NjJlZjBiMzRkNGUwMzNjMzYwZDU5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zPpztr5wp4RIr_BDqVSzsrXO_k2SEdPIMJ0Gpj8e3vA)
> 
> 正如您在所附照片中看到的。

thank you very much!

**Comment by Metick** [comment]
> > > > 您要找的那个不在win32ksgd.sys。可以在 win32kbase.sys 中找到偏移量，在 NtUserGetAsyncKeyState 函数中，你将找到要查找的偏移量。![图像](https://private-user-images.githubusercontent.com/45372336/363491154-2450d85b-35d2-4338-930d-5f372161e4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMTA4NzcsIm5iZiI6MTcyNTIxMDU3NywicGF0aCI6Ii80NTM3MjMzNi8zNjM0OTExNTQtMjQ1MGQ4NWItMzVkMi00MzM4LTkzMGQtNWYzNzIxNjFlNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE3MDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjY1MGZmZjg5ZWM5NWI2ZWIzZjg5MTIzYzlmYzQzMDc2MzZkOTc3M2YxYmJiYTVlNGM5YzAwN2M2MGY4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XNmkOHh7s2cW2on2PfH0YDhdhT28HtPN1G1SfGX0nxQ)正如您在所附照片上看到的那样。
> > > 
> > > 
> > > Xbox 有什么方法可以获取状态吗
> > 
> > 
> > 您会说英语吗？
> 
> Sorry, my English isn't very good. How do I get the button state of a game controller?

You don't you need dinput and xinput for that. aka just read the ingame input system instead.
