### ISSUE TITLE
CR3 Help

### ISSUE THREAD

**Issue by lishaoju** [Metick/DMALibrary#35]
> while (true) {
				BYTE bytes[4] = { 0 };
				DWORD i = 0;
				if (VMMDLL_VfsReadU(this->vHandle, const_cast<LPSTR>("\\misc\\procinfo\\progress_percent.txt"), bytes, 3, &i, 0) == VMMDLL_STATUS_SUCCESS) {
					if (atoi(reinterpret_cast<LPSTR>(bytes)) == 100) {
						break;
					}
				}
				sleep_for(milliseconds(100));
}

When CR3 patching fails, I attempt to repatch it, but every time I start retrieving the data from 0 again, and I can never successfully patch CR3. Some systems behave this way. Normally, on the second attempt, the retrieval should directly start from 100. How should I handle this issue?

**Comment by Metick** [comment]
Restart pc, it just means it got paged out.

**Comment by lishaoju** [comment]
> Restart pc, it just means it got paged out.

Thank you for your prompt response

**Comment by lishaoju** [comment]
> Restart pc, it just means it got paged out.

Are there any other solutions? I've tried restarting the PC multiple times, but it doesn't seem to have any effect

**Comment by Metick** [comment]
cold restart, and make sure youre restarting your target computer

**Comment by lishaoju** [comment]
> cold restart, and make sure youre restarting your target computer

It's still not resolved. Could this be related to the system? Windows 10 Professional 22H2 19045.4780 is not working, but Windows 10 Professional 22H2 19045.3803 is working

**Comment by Metick** [comment]
Probably not. Just page issues.

**Comment by dolodi** [comment]
Its beacause your probably initializing all plugins each time, so progress has to start from 0 again
