### ISSUE TITLE
Keyboard keys reading stopped working after win update

### ISSUE THREAD

**Issue by kWAYTV** [Metick/DMALibrary#37]
![image](https://github.com/user-attachments/assets/31fe8c26-3df5-4751-a70c-d149475bd66e)

**Comment by kWAYTV** [comment]
![image](https://github.com/user-attachments/assets/1a9c18bb-17b6-4f94-80d9-bfcb49a02d17)
![image](https://github.com/user-attachments/assets/f27eefd8-2719-4f0c-829c-d2bc360adfc1)
![image](https://github.com/user-attachments/assets/8b2f97cd-aed9-46b1-99e5-8f4b2705bf92)

**Comment by kWAYTV** [comment]
[dumps.zip](https://github.com/user-attachments/files/17364990/dumps.zip)

**Comment by Metick** [comment]
#41 should've solved the issue.
