### ISSUE TITLE
win11 Keyboard

### ISSUE THREAD

**Issue by zhang2651** [Metick/DMALibrary#39]
This is win11 24h2 win32kbase.sys found inside, I don't know if it's correct
![image](https://github.com/user-attachments/assets/505d263c-2cd1-432d-9083-61680d7ad080)

**Comment by kWAYTV** [comment]
There are multiple issues open about it, including one by me, lets try to stick to one and figure this out

[Seems this one is the most advanced one](https://github.com/Metick/DMALibrary/issues/32#top)

**Comment by kaimu-kun** [comment]
Problem should be resolved with last merge
