### ISSUE TITLE
Should verify the `VMMDLL_MemReadEx` actual bytes read.

### ISSUE THREAD

**Issue by kweatherman** [Metick/DMALibrary#9]
I ran into this issue and notice all DMA sources I've examined don't verify the `VMMDLL_MemReadEx` the read byte count.  
The reads can definitely fail. For instance I was using the `VMMDLL_FLAG_NOPAGING` trying to read from a process image.  
In turned out that it was failing because the memory pages were not paged in.  
`VMMDLL_MemReadEx` returned `true` but was only reading part of the memory.  
I only found this out by verifying  `pcbReadOpt` actually read count during troubleshooting.

Notice here for the `VMMDLL_MemRead` function in the MemProcFS source:  
https://github.com/ufrisk/MemProcFS/blob/master/vmm/vmmdll.c#L745  
There is such a check `&& (dwRead == cb)`

So a suggestion if you want to catch potential problems, you could add these  `&& (dwRead == cb)` type checks to calls like:  
https://github.com/Metick/DMALibrary/blob/Master/DMALibrary/Memory/Memory.cpp#L663

**Comment by Metick** [comment]
You're absolutely right on this. Personally I've never had this happen to me before, but there is always that chance that it can happen. I will add a check for it on the library once I have time for it, or feel free to send a PR for it.
